export default function GeneralInformation({
  userData,
  editGeneral,
  handleInput,
}) {
  return (
    <>
      <h2>General Information</h2>

      <>
        <label>
          Name:
          <input
            name="fullName"
            placeholder="John Smith"
            type="text"
            onChange={handleInput}
            value={userData.fullName}
            disabled={editGeneral}
          />
        </label>
        <label>
          Email:
          <input
            name="email"
            placeholder="example@email.com"
            type="email"
            onChange={handleInput}
            value={userData.email}
            disabled={editGeneral}
          />
        </label>
        <label>
          Location:
          <input
            name="location"
            placeholder="1 NW Miami"
            type="text"
            onChange={handleInput}
            value={userData.location}
            disabled={editGeneral}
          />
        </label>
        <label>
          Portfolio:
          <input
            name="portfolio"
            placeholder="example.com"
            type="text"
            onChange={handleInput}
            value={userData.portfolio}
            disabled={editGeneral}
          />
        </label>
        <label>
          LinkedIn:
          <input
            name="linkedin"
            placeholder="example.com"
            type="text"
            onChange={handleInput}
            value={userData.linkedin}
            disabled={editGeneral}
          />
        </label>
        <label>
          Github:
          <input
            name="github"
            placeholder="example.com"
            type="text"
            onChange={handleInput}
            value={userData.github}
            disabled={editGeneral}
          />
        </label>
        <label>
          Attach Photo
          <input
            name="photo"
            placeholder="your-photo.jpg"
            type="file"
            onChange={handleInput}
            disabled={editGeneral}
          />
        </label>
      </>
    </>
  );
}
